# Generated by Django 4.2.6 on 2025-03-02 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parents', '0001_initial'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sostudentparent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='Students.sostudent'),
        ),
        migrations.AddField(
            model_name='sostudentoff',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='Parents.soparent'),
        ),
        migrations.AddField(
            model_name='sostudentoff',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='Students.sostudent'),
        ),
        migrations.AlterUniqueTogether(
            name='sostudentparent',
            unique_together={('student', 'parent')},
        ),
    ]
