# Generated by Django 5.1.6 on 2025-03-02 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='Parents.soparent')),
            ],
        ),
    ]
