# Generated by Django 5.1.6 on 2025-03-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parents', '0003_otpparents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokenparents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='Parents.soparent')),
            ],
        ),
    ]
