# Generated by Django 5.1.6 on 2025-03-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parents', '0004_tokenparents'),
    ]

    operations = [
        migrations.AddField(
            model_name='soparent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sostudentoff',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sostudentparent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
