# Generated by Django 4.2.6 on 2025-03-02 04:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SoStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.BooleanField()),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('so_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Students.soclass')),
            ],
        ),
        migrations.CreateModel(
            name='SoCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_time', models.DateTimeField()),
                ('check_type', models.BooleanField()),
                ('note', models.TextField(blank=True, null=True)),
                ('so_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.soclass')),
            ],
        ),
    ]
