# Generated by Django 5.1.6 on 2025-03-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socheckin',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soclass',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sostudent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
