# Generated by Django 4.2.6 on 2025-03-02 04:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoBlog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('count_view', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('relation_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
