# Generated by Django 5.1.6 on 2025-03-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soblog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
