# Generated by Django 5.1.6 on 2025-03-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='souser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
