# Generated by Django 5.1.6 on 2025-03-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_souser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorole',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='souser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='souserrole',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
